return {
  ui = {
    BookMark = "",
    Bug = "",
    Calendar = "",
    Check = "",
    ChevronRight = ">",
    Circle = "",
    Close = "",
    Code = "",
    Comment = "",
    Dashboard = "",
    Fire = "",
    Gear = "",
    History = "",
    Lightbulb = "",
    List = "",
    Lock = "",
    NewFile = "",
    Note = "",
    Package = "",
    Pencil = "",
    Project = "",
    Search = "",
    SignIn = "",
    Tab = "",
    Table = "",
    Telescope = "",
  },
  diagnostics = {
    Error = "",
    Hint = "",
    Information = "",
    Question = "",
    Warning = "",
  },
  lsp = {
    server_installed = "✓",
    server_pending = "➜",
    server_uninstalled = "✗",
  },
  git = {
    Add = "",
    Branch = "",
    Diff = "",
    Ignore = "◌",
    Mod = "",
    Octoface = "",
    Remove = "",
    Rename = "➜",
    Repo = "",
    Staged = "S",
    Unmerged = "",
    Unstaged = "",
    Untracked = "U",
  },
  winbar = {
    FileIcon = "",
  },
}
